### ISSUE TITLE
Distributing assignments

### ISSUE THREAD

**Issue by hershaw** [LDSSA/instructors-forum#1]
## Problem

One of the biggest issues from the first LDSSA class was that we didn't have graded assignments which created two main problems

- Students didn't have a way to know if something was implemented correctly
- We didn't have a good sense of progress for the students.

## Proposal

In order to solve this for a subset of the problem sets that a student might work on I propose using a few technologies in conjunction with each other

- [JupyterHub](https://jupyterhub.readthedocs.io/en/latest/) 
    - An environment for hosting notebook environments for multiple users.
    - Each student would get their own login which will give them their own notebooks that
       the other students cannot access.
- [nbgrader](http://nbgrader.readthedocs.io/en/stable/)

While students should still do heavy work on their own machines, small and well-defined
problems can be distributed and graded on JupyterHub notebooks using nbgrader.

This would be a bit of extra work on our side because we would have to host JupyterHub on our
own machine and manage students.

I'm currently looking into the feasibility of this approach but it looks promising. For more info, please take a look at a demo of [nbgrader](https://youtu.be/5WUm0QuJdFw) here.

**Comment by jtascensao** [comment]
Have you tried this before @hershaw? Are there any other alternatives we could be exploring in parallel?

**Comment by jtascensao** [comment]
Just watched the video on nbgrader, looks super promising. Possibly I'm missing something, but I think we can do without JupyterHub, just distributing student versions via GitHub and creating an email account to receive the submissions, if needed. We could then reply with the feedback.

**Comment by echo66** [comment]
Also, we should explore things like [Google Colab](https://colab.research.google.com/). It allows students to use all the tools they will probably need without having to worry about local environments.

**Comment by hershaw** [comment]
@jtascensao yes you can do it without JupyterHub but it adds a few manual steps. 

We need to get a test running to see how much work it would actually save.

@echo66 never see google colab! will check that out!

**Comment by PedroGFonseca** [comment]
It could be argued that they should learn how to work with the real world environments. Having them too comfortable might lead to them being weaker when it's time to do hackathons. 

On the flip side, it would simplify things with Windows machines, etc

**Comment by hershaw** [comment]
Well they should definitely be able to run the environment on their own machines - it's not that hard and very useful to know how.

I'm mostly just concerned with the grading workflow.

**Comment by PedroGFonseca** [comment]
In that case I'm all for whatever is easier, and we should then add another unit on "setup and workflow" to ensure they know how to live outside of hosted notebooks

**Comment by hershaw** [comment]
We do have the [setup repo](https://github.com/LDSSA/setup) and last time everyone showed up already ready to go on it so I think we are cool with that. If we have another requirement the down side of it is that they will need to maintain another login to another system.

Going to take a look at google colab real quick.

**Comment by hershaw** [comment]
Google collaboratory looks really cool but there's no way to distribute and grade assignments.

I think that the best we are looking at right now is jupyterhub with nbgrader still...

**Comment by echo66** [comment]
@hershaw , are these assignments the ones used for admission into the academy? or what?
