### ISSUE TITLE
Summarize the student's feedback 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/instructors-forum#10]
We asked students for feedback on a number of occasions, some in structured numerical form, and some in free text form. 

We need to do the following: 
- [ ] get feedback form the last hackathon
- [ ] collect all the feedback together 
- [ ] "digest it" into easy to consume formats
- [ ] Extract the key conclusions 
- [ ] Transform them into practical recommendations for the next edition of the Academy

**Comment by echo66** [comment]
Where are the forms responses, @PedroGFonseca?

**Comment by PedroGFonseca** [comment]
They are scattered, i need to get them together
