### ISSUE TITLE
Add expected output to the exercises 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/instructors-forum#11]
One of the interesting things in Coursera is that, while you cannot have the solution to the exercises, you generally have the expected output. This makes learning exercises "test-driven-development", where you know what output you should be getting, and are trying to figure out the logic. 

In order to achieve this, we need to better constrain the first few exercises of each learning unit, to allow students to focus only on the **new** material. After the first few exercises, the exercise notebook can then start removing format and asking more open questions, so that students also have the real world experience of having to structure the problem themselves. 

The following is an example from [Coursera's Deep Learning course](https://www.coursera.org/learn/neural-networks-deep-learning/home/welcome). Note the "_START CODE HERE_" sections in the function, and then the cells that the student has to run to get (or not!) the expected output. 

This can later be also graded, giving us live feedback about how well the students are learning and who needs help, but that is being the scope of this issue. 

![pasted_image_at_2018_01_26_09_19_am](https://user-images.githubusercontent.com/8465611/35535503-b518a53a-053b-11e8-9980-b9bef53552ea.png)

**Comment by hershaw** [comment]
With nbgrader you can have the option to show the unit tests to the students when they are running it. That will help them understand what their python code is supposed to be returning but not for the visual part which is what I think you are talking mostly about here.
