### ISSUE TITLE
Calendar and structure of the next Academy 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/instructors-forum#12]
There are a number of things that need defining, and others that just need announcing: 
- [ ] When is the kickoff day of the next Academy? 
- [ ] When do we start accepting students? 
- [ ] When do we close applications?
- [ ] How many learning units?
- [ ] How many hackathons will they be? 
- [ ] Should the Kickoff days be 3 consecutive days or 2 consecutive weekends? 
- [ ] Are all instructors expected to come to all kickoff days, or do they take shifts?

**Comment by HugoDLopes** [comment]
Price is a very important subject. Also, since this is a non-profit, the costs should at least be made available to all of the monitors :) so that we can also give recommendations and ideas (spend there, cut there)

**Comment by HugoDLopes** [comment]
Another question. Who are the monitors right now? I saw a lot of people in the beginning and just a few survived through time. Did they quit? Are they still around? Would be good to understand our "mass"
