### ISSUE TITLE
Entrance test

### ISSUE THREAD

**Issue by hershaw** [LDSSA/instructors-forum#14]
We need to decide on how to do the entrance test and what it should include. It should still be a python test but it needs to be much more automated than it was last time. 

I propose the following criteria:

- it should be a bit harder than it was last time. There were too many folks that got in that didn’t know how to code well enough and I think this accounted for a large number of the dropouts. 
- it should be timed. Once you start it you only have e.g. 24 hours. 
- you should be able to start whenever you want. Since we will be first come first served basis, they will be incentivized to start earlier. 

Does anyone know of a platform that can do this?

**Comment by PedroGFonseca** [comment]
We saw something like this when we were evaluating alternatives. There is [Codility](https://www.codility.com/), not sure whether we could get a sponsorship deal where they let us use their platform for free, as it's quite expensive. 

A couple of suggestions: 
1) We should evaluate basic unix abilities, can you `git pull`, `git clone`, `ls`, etc 
2) One way to discourage cheating might be to have the written exam remote, followed by a 5 minute oral exam over Skype. If they know they are going to be questioned, they will hesitate to ask a friend to do it for them. We can just ask basic questions they've already answered in their written form (_"You used a for loop here, can you explain your reasoning?"_). Should be pretty obvious if they didn't do it themselves.
3) As for grading itself, can't we use the same approach we will be using with the learning units, and use NBgrader?

**Comment by echo66** [comment]
We could also use hacker rank. It allows people to create code exams with a time limit.

**Comment by manugarri** [comment]
+1 for testing git. We were updating our learning units even hours before the class and if we could ensure students knew how to make a pull right before the class if needed that would be a huge relief for the teachers.
