### ISSUE TITLE
Give students write access to [S|B]LU repos?

### ISSUE THREAD

**Issue by hershaw** [LDSSA/instructors-forum#15]
This way they can contribute directly to the repositories and be able to add tags to issues which they currently cannot do.

The master branch will always stay protected to all of these repos.

I'm in favor of doing so. The more permissions we can give them, the more we empower them, and the better the learning material will be. Even if we just get one or two students contributing on a regular basis, this can still be considered a huge win.

If we want to do this, we can create a Batch2 github team and add all of them to it and give them write access to the repos as they are developed.

**Comment by PedroGFonseca** [comment]
I'm for it :)

**Comment by hcastilho** [comment]
I'm very cautious about this.

We need to maintain 2 versions of the exercise notebooks, the instructors and the students. And the students version should not be edited directly.
I was going for a model of having 2 repos <batch>-<LU>-instructors and <batch>-<LU> for the students. With the intructors version being the single source of truth. We can change this and have the instructors repo only having the exercerise notebook and the students being the source of truth for everything except the exercise notebook. Not a problem, it's probably a better model (comments?).

We need too be very careful about the permissions of each team, and people not in teams.
* Restrict default view repo permissions to forbid (we have repos we don't want them to see)
* Restric default create repo permission
* Restrict permissions on the master branch for every repo that they have access to
I'm sure there's more, it's hard to get everything right.

I know it's harder, but I'm for keeping PR's.
