### ISSUE TITLE
Best model to keep track of changes in learning units

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/instructors-forum#16]
Due to the use of nbgrader we have 2 versions of the exercise notebooks, the instructors and the students. For this notebook the single source of truth is the instructors version, but we need to keep it private.

One solution is to have everything in an instructors repo and let it be the single source of truth with the students version being just a front for the operation.

Another is to let the students version be the source of truth for everything except the exercise notebook. We need to be more careful not to change the exercise notebook, but makes PR's easier.

Or maybe some other model, open to ideas.

**Comment by PedroGFonseca** [comment]
Not important: one caveat I noticed when trying to do everything on the Instructors repo, was that every time I wanted to fix a tiny thing on the readme (generally typos, or adding some extra link) I'd have to bother Castilho. 

Maybe we shouldn't change anything on the student version, except for the readme?

**Comment by hcastilho** [comment]
I'm pro private repo only with data and (instructors) exercise notebook.
It makes it easier for instructors to make changes.
But it does mean that they have to have discipline and not changing the student notebook directly.
