### ISSUE TITLE
Should we use this forum for every decision, or only for technical ones? 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/instructors-forum#3]
Some decisions are not technical, and the Academy staff has non-technical people (e.g. ops/communication). 

Should questions which aren't technical be discussed here (risking excluding non-technical people)? 

Examples: 

> - What should be the dates for the hackathons? 
> - Should we use the same level of catering as last year, or should we save some money? 
> - How many times can a student not show up before being excluded? 

Should we conclude that these questions should not be discussed here, where should they go?

**Comment by jtascensao** [comment]
Non-technical people possibly don't even have a GitHub account. Any inconvenient sticking with Slack for those?

**Comment by PedroGFonseca** [comment]
The only (serious) downside of slack is that conversations get lost in the scroll. My suggestion would be to use Google Docs to discuss non technical matters. 

That does however require setting rules for 
- What discussions happen in this forum 
- What discussions happen on the alternative [slack, gdocs, etc]

**Comment by jtascensao** [comment]
What about using a "fuller" stack alternative, such as Asana/Trello/Basecamp/Jira, for everyone? Is it overkill?

A team our size should be able to work on the free tier of both Asana and Trello, at least.

**Comment by HugoDLopes** [comment]
I don't know if github is the best place to have these discussions, but we can give it a try.

**Comment by hershaw** [comment]
For task management we might want to another tool like Trello or Asana. I was thinking that the purpose of this is repo is to allow us to set a subject of conversation and be able to keep a threaded conversation going that doesn't get lost in slack and has a bit more expressivity.

For example this conversation - we now have a way to look at what people are saying about what we should use it for. It's searchable and very clearly associated with a subject which is the title.

I'm totally 100% open to more suggestions and if this doesn't work we can totally ditch it and never turn back :) However, I think that this is a decent option to at least start with and if it doesn't work we can have some more specific stuff to look for.

As far as what we should use this forum for I'll suggest the following:

*Any discussion about classes and class content that is relevant to 1 or more instructors*

What do you guys think of that?

**Comment by PedroGFonseca** [comment]
_"Classes and class content"_ content sounds good, I would suggest adding _technical questions_ too. How about the following definition: 

_The **instructors forum** is for technical and/or curriculum related questions and problems, where only instructors are involved in the decision-making process. **Issues** can either be posed as questions for discussion or as problems that need solving. They should be **closed** when either the problem has been solved, or the question discussion has lead to a final decision._

Of the currently open issues, the following would make it: 
> Submissions evaluation tool?
> Add expected output to the exercises enhancement
> Calendar and structure of the next Academy
> Deployment Hackathon Duration and Engagement
> Improve content of learning units enhancement
> Consistency between learning units enhancement
> How to avoid cheating in the entry tests?
> Entrance test


And the following would not: 

> Team for the next Academy
> Summarize the student's feedback 
> What should be the criteria for students to be considered graduates?
> Distributing assignments

This second group would be re-written either as Trello cards or discussed on slack.
