### ISSUE TITLE
How to avoid cheating in the entry tests? 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/instructors-forum#6]
We have entry tests to ensure a sufficient level of Python. The first edition showed that we have a weakness in grading, as at least one student has obviously cheated to get in. 

What measures can be taken to avoid teaching in future?

**Comment by echo66** [comment]
Was the entry exam the same for *everyone*?

**Comment by PedroGFonseca** [comment]
It was, however given that students had friends do the test for them having different tests would not have saved us

**Comment by hershaw** [comment]
yeah let's see what Elena comes up for this one...

**Comment by manugarri** [comment]
One option is to do an in person test, with limited amount of time, kinda like standardized tests (SAT, TOEFL, etc) do.

Im not a big fan though, but self reported solutions will not avoid cheating.

**Comment by echo66** [comment]
We could generate tests for each person. Or am I missing something?

**Comment by PedroGFonseca** [comment]
@echo66 that would not really solve the issue, because (from what we understand) they had friends who knew python solve the problem for them

**Comment by HugoDLopes** [comment]
I don't see this being solved with tests being done without our supervision... It is really difficult to overcome. Possible solutions:
- We either have students in-house doing the entry-exam
- We create multiple challenges and randomly assign them to students making it more difficult to copy
- We make the challenge online with a timer (reduces chance of copy)
- We let them copy and keep warning them that we use extremely advanced algorithms to check, they will be disqualified, and it is not acceptable by any means.

**Comment by PedroGFonseca** [comment]
Slightly duplicated from #14 : 

> One way to discourage cheating might be to have the written exam remote, followed by a 5 minute oral exam over Skype. If they know they are going to be questioned, they will hesitate to ask a friend to do it for them. We can just ask basic questions they've already answered in their written form ("You used a for loop here, can you explain your reasoning?"). Should be pretty obvious if they didn't do it themselves.

**Comment by PedroGFonseca** [comment]
Closing this thread to discuss it only on https://github.com/LDSSA/instructors-forum/issues/14 (got duplicated)
