### ISSUE TITLE
Team for the next Academy 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/instructors-forum#7]
We need to define who is the team for the next edition of the Academy, and what is the effort expected of each position.

Positions (suggestion): 
- Leadership 
    - Academy leader
    - Headteacher 
- Teacher 
- Monitor 
- Communications 
- Operations

**Comment by hershaw** [comment]
We can start off by asking people about how much time they spent preparing hackathons.

I did hackathon-3 and hackathon-6. 6 was a bit much and is an outlier so I'll only mention 3.

I spent about 10 hours per week on it including making the learning units for a total of 40 hours. The time was split more or less as follows:

- 5 hours talking with people about what to teach
- 3 hours writing the hackathon doc and iterating on it
- 10 (~3*3) hours for each of the learning units
- 10 hours finding dataset
- 4 hours prepping dataset
- 5 hours communication with students
- another 6 or so hours on misc stuff that I don't remember

I would say that the time will go down by about 1/2 for the next one and most of the effort will be in finding and preparing a good dataset. The rest will be iteration on the learning units.

What about the rest of you guys? How much time did you spend preparing hackathons?

**Comment by HugoDLopes** [comment]
I was responsible for hackathon-1 and participated in the preparation of two more (if I'm not mistaken). I don't fully remember the time (the first hackathon was lighter) I took but I would say at the minimum (considering experience from participation in the other ones):
- 1 hour to come up with good idea
- 4 hours finding dataset
- 8 hours preparing dataset and structuring problem
- 8 hours preparing learning notebooks (2)
- 2 hours helping students (never too active...)
- 10 hours, the day of the hackathon
- 1-2 hours closing hackathon afterwards
